/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.comci.imgp.ui;

import javax.swing.JFrame;

/**
 *
 * @author Sebastian
 */
public class FullscreenFrame extends javax.swing.JFrame {

    /**
     * Creates new form FullscreenFrame
     */
    public FullscreenFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePuzzlePanelFullscreen = new de.comci.imgp.ui.ImagePuzzlePanel();

        setTitle("Fullscreen");
        setAlwaysOnTop(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);

        javax.swing.GroupLayout imagePuzzlePanelFullscreenLayout = new javax.swing.GroupLayout(imagePuzzlePanelFullscreen);
        imagePuzzlePanelFullscreen.setLayout(imagePuzzlePanelFullscreenLayout);
        imagePuzzlePanelFullscreenLayout.setHorizontalGroup(
            imagePuzzlePanelFullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        imagePuzzlePanelFullscreenLayout.setVerticalGroup(
            imagePuzzlePanelFullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePuzzlePanelFullscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePuzzlePanelFullscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.comci.imgp.ui.ImagePuzzlePanel imagePuzzlePanelFullscreen;
    // End of variables declaration//GEN-END:variables

    void setImagePuzzleModel(ImagePuzzleModel model) {
        imagePuzzlePanelFullscreen.setModel(model);
    }
}
